### ISSUE TITLE
Problems encountered during training

### ISSUE THREAD

**Issue by ZWXCV** [joslefaure/HIT#32]
The following error occurs when executing "python train_net.py --config-file "config_files/hitnet.yaml"

Traceback (most recent call last):
  File "train_net.py", line 255, in <module>
    main()
  File "train_net.py", line 245, in main
    args.no_head)
  File "train_net.py", line 100, in train
    mem_active,
  File "/root/autodl-tmp/HIT-master/hit/engine/trainer.py", line 59, in do_train
    loss_dict, weight_dict, metric_dict, pooled_feature = model(slow_video, fast_video, boxes, objects, keypoints, mem_extras)
  File "/root/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/HIT-master/hit/modeling/detector/action_detector.py", line 20, in forward
    result, detector_losses, loss_weight, detector_metrics = self.roi_heads(slow_features, fast_features, boxes, objects, keypoints, extras, part_forward)
  File "/root/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/HIT-master/hit/modeling/roi_heads/roi_heads_3d.py", line 12, in forward
    result, loss_action, loss_weight, accuracy_action = self.action(slow_features, fast_features, boxes, objects, keypoints, extras, part_forward)
  File "/root/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/HIT-master/hit/modeling/roi_heads/action_head/action_head.py", line 44, in forward
    x, x_pooled, x_objects, x_keypoints, x_pose = self.feature_extractor(slow_features, fast_features, proposals, objects, keypoints, extras, part_forward)
  File "/root/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/HIT-master/hit/modeling/roi_heads/action_head/roi_action_feature_extractor.py", line 145, in forward
    ia_feature, res_person, res_object, res_keypoint = self.hit_structure(person_pooled, proposals, object_pooled, objects, hands_pooled, keypoints, memory_person, None, None, phase="rgb")
  File "/root/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/HIT-master/hit/modeling/roi_heads/action_head/hit_structure.py", line 213, in forward
    mem_feature, phase)
  File "/root/autodl-tmp/HIT-master/hit/modeling/roi_heads/action_head/hit_structure.py", line 230, in _reduce_dim
    query = self.person_dim_reduce(person)
  File "/root/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 590, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 586, in _conv_forward
    input, weight, bias, self.stride, self.padding, self.dilation, self.groups
TypeError: conv3d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)

I hope the author can give some answers. Thank you very much

**Comment by ZWXCV** [comment]
The question has been solved. Thank you for your answer

**Comment by fengjingchehu** [comment]
I want to know if you still have the pre-trained model and JHMDB model?

**Comment by fengjingchehu** [comment]
I wonder how you solved this problem? Because I have encountered the same issue.Looking forward to your reply.
