### ISSUE TITLE
get frame mAP error

### ISSUE THREAD

**Issue by ZWXCV** [joslefaure/HIT#34]
Thanks for the author's reply, I can indeed get videomAP through the instruction. I want to get the frame mAP and I see that the parameter "frameAP " exists in compute_video_map.py, so I execute the instruction "python compute_video_map.py frameAP JHMDB-GT.pkl result_jhmdb.pkl". But I get a syntax error. The following is the error message:
Traceback (most recent call last):
File "compute_video_map.py", line 427, in
frameAP(args.groundtruth, args.detections, args.thr)
File "compute_video_map.py", line 86, in frameAP
detections = alldets[alldets[:, 2] == ilabel, :]
TypeError: unhashable type: 'slice'
According to the error message TypeError: unhashable type: 'slice', the slicing operation cannot be applied to NumPy arrays.
This makes me very confused, I hope the author can give an answer,thank you very much.

**Comment by joslefaure** [comment]
Please follow[ these instructions](https://github.com/joslefaure/HIT/blob/master/GETTING_STARTED.md#inference) for frameAP calculations

**Comment by joslefaure** [comment]
`python evaluation_ucf24_jhmdb/pascalvoc.py --gtfolder groundtruths_jhmdb --detfolder PATH-TO-DETECTIONS-FOLDER`

**Comment by ZWXCV** [comment]
Thank you for the author's reply, but why is the value of video mAP that I received significantly different from the value given in your paper, about 5%? I hope the author can provide some suggestions. Thank you very much
