### ISSUE TITLE
pip install -e . raise error in ROIAlign3d_cuda.cu (Windows)

### ISSUE THREAD

**Issue by dtraparic** [joslefaure/HIT#45]
Hello,

I was following the guide install.md, I'm on Windows 10, Pytorch installed for cuda11.3, GTX 1660 Ti, and here's my error when trying `pip install -e .`
I isolated the entire error by running only `python setup.py develop`

```
C:\Users\David Traparic\Documents\prog\HITNet\HIT-master>python setup.py develop
running develop
C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing hit.egg-info\PKG-INFO
writing dependency_links to hit.egg-info\dependency_links.txt
writing requirements to hit.egg-info\requires.txt
writing top-level names to hit.egg-info\top_level.txt
C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\utils\cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'hit.egg-info\SOURCES.txt'
writing manifest file 'hit.egg-info\SOURCES.txt'
running build_ext
C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\utils\cpp_extension.py:316: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
building 'hit._custom_cuda_ext' extension
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc" -c "C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc\cuda\ROIAlign3d_cuda.cu" -o "build\temp.win-amd64-cpython-37\Release\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc\cuda\ROIAlign3d_cuda.obj" "-IC:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\torch\csrc\api\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\TH" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\THC" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --use-local-env
ROIAlign3d_cuda.cu
C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu(277): error: no instance of function template "THCCeilDiv" matches the argument list
            argument types are: (long long, long)

C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu(277): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, long)

C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu(324): error: no instance of function template "THCCeilDiv" matches the argument list
            argument types are: (int64_t, long)

C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu(324): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, long)

4 errors detected in the compilation of "C:/Users/David Traparic/Documents/prog/HITNet/HIT-master/hit/csrc/cuda/ROIAlign3d_cuda.cu".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.3\\bin\\nvcc.exe' failed with exit code 1
```

I'm not very good in C compilation and low-level errors, do somebody knows what all this means ?

David

**Comment by joslefaure** [comment]
I have not tested the program on windows therefore I can't know for sure. Make sure you have torch 1.7.1

**Comment by dtraparic** [comment]
I've just installed torch 1.7.1 but I still get a similar error.

```
C:\Users\David Traparic\Documents\prog\HITNet\HIT-master>python setup.py develop
running develop
C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing hit.egg-info\PKG-INFO
writing dependency_links to hit.egg-info\dependency_links.txt
writing requirements to hit.egg-info\requires.txt
writing top-level names to hit.egg-info\top_level.txt
reading manifest file 'hit.egg-info\SOURCES.txt'
writing manifest file 'hit.egg-info\SOURCES.txt'
running build_ext
C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'hit._custom_cuda_ext' extension
Emitting ninja build file C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\build\temp.win-amd64-cpython-37\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA "-IC:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\torch\csrc\api\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\TH" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\THC" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -c "C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu" -o "C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\build\temp.win-amd64-cpython-37\Release\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc\cuda\ROIAlign3d_cuda.obj" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
FAILED: C:/Users/David Traparic/Documents/prog/HITNet/HIT-master/build/temp.win-amd64-cpython-37/Release/Users/David Traparic/Documents/prog/HITNet/HIT-master/hit/csrc/cuda/ROIAlign3d_cuda.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA "-IC:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\torch\csrc\api\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\TH" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\THC" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -c "C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu" -o "C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\build\temp.win-amd64-cpython-37\Release\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc\cuda\ROIAlign3d_cuda.obj" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu(277): error: no instance of function template "THCCeilDiv" matches the argument list
            argument types are: (long long, long)

C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu(277): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, long)

C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu(324): error: no instance of function template "THCCeilDiv" matches the argument list
            argument types are: (int64_t, long)

C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIAlign3d_cuda.cu(324): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, long)

4 errors detected in the compilation of "C:/Users/David Traparic/Documents/prog/HITNet/HIT-master/hit/csrc/cuda/ROIAlign3d_cuda.cu".
ROIAlign3d_cuda.cu
[2/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA "-IC:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\torch\csrc\api\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\TH" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\THC" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -c "C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIPool3d_cuda.cu" -o "C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\build\temp.win-amd64-cpython-37\Release\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc\cuda\ROIPool3d_cuda.obj" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
FAILED: C:/Users/David Traparic/Documents/prog/HITNet/HIT-master/build/temp.win-amd64-cpython-37/Release/Users/David Traparic/Documents/prog/HITNet/HIT-master/hit/csrc/cuda/ROIPool3d_cuda.obj
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\nvcc --use-local-env -Xcompiler /MD -Xcompiler /wd4819 -Xcompiler /wd4251 -Xcompiler /wd4244 -Xcompiler /wd4267 -Xcompiler /wd4275 -Xcompiler /wd4018 -Xcompiler /wd4190 -Xcompiler /EHsc -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -DWITH_CUDA "-IC:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\torch\csrc\api\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\TH" "-IC:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\include\THC" "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\include" "-IC:\Users\David Traparic\miniconda3\envs\hit\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -c "C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIPool3d_cuda.cu" -o "C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\build\temp.win-amd64-cpython-37\Release\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit/csrc\cuda\ROIPool3d_cuda.obj" -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -O3 -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_custom_cuda_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=sm_75
C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIPool3d_cuda.cu(131): error: no instance of function template "THCCeilDiv" matches the argument list
            argument types are: (long long, long)

C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIPool3d_cuda.cu(131): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, long)

C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIPool3d_cuda.cu(180): error: no instance of function template "THCCeilDiv" matches the argument list
            argument types are: (int64_t, long)

C:\Users\David Traparic\Documents\prog\HITNet\HIT-master\hit\csrc\cuda\ROIPool3d_cuda.cu(180): error: no instance of overloaded function "std::min" matches the argument list
            argument types are: (<error-type>, long)

4 errors detected in the compilation of "C:/Users/David Traparic/Documents/prog/HITNet/HIT-master/hit/csrc/cuda/ROIPool3d_cuda.cu".
ROIPool3d_cuda.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\utils\cpp_extension.py", line 1539, in _run_ninja_build
    env=env)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 121, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\command\develop.py", line 34, in run
    self.install_for_development()
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\command\develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 468, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 494, in _build_extensions_serial
    self.build_extension(ext)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 556, in build_extension
    depends=ext.depends,
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\utils\cpp_extension.py", line 652, in win_wrap_ninja_compile
    with_cuda=with_cuda)
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\utils\cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\David Traparic\miniconda3\envs\hit\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

Thanks anyway, it's probably due to windows
