### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by fengjingchehu** [joslefaure/HIT#46]
HIT-master$ python test_net.py --config-file "config_files/hitnet.yaml" MODEL.WEIGHT "data/models/J-HMDB/model_J-HMDB.pth"
Traceback (most recent call last):
  File "test_net.py", line 8, in <module>
    from hit.modeling.detector import build_detection_model
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/HIT-master/hit/modeling/detector/__init__.py", line 1, in <module>
    from .action_detector import build_detection_model
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/HIT-master/hit/modeling/detector/action_detector.py", line 3, in <module>
    from ..backbone import build_backbone
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/HIT-master/hit/modeling/backbone/__init__.py", line 1, in <module>
    from .backbone import build_backbone
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/HIT-master/hit/modeling/backbone/backbone.py", line 2, in <module>
    from . import slowfast, i3d
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/HIT-master/hit/modeling/backbone/slowfast.py", line 6, in <module>
    from hit.modeling.common_blocks import ResNLBlock
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/HIT-master/hit/modeling/common_blocks.py", line 2, in <module>
    from hit.modeling.nonlocal_block import NLBlock
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/HIT-master/hit/modeling/nonlocal_block.py", line 6, in <module>
    from hit.layers import FrozenBatchNorm3d
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/HIT-master/hit/layers/__init__.py", line 3, in <module>
    from .roi_align_3d import ROIAlign3d
  File "/mnt/745425dc-5d5b-4490-9d38-57169dcb2ab3/wxl/HIT-master/hit/layers/roi_align_3d.py", line 7, in <module>
    import hit._custom_cuda_ext as _C
ImportError: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory

i already install hit 
Using /home/user/anaconda3/envs/hit/lib/python3.8/site-packages
Finished processing dependencies for hit==0.0.0

**Comment by NWAFU-YcZhang** [comment]
hello, how do you fixed this problem?  I am facing with the same question. Thank you
