### ISSUE TITLE
error with test_net.py

### ISSUE THREAD

**Issue by hhh804** [joslefaure/HIT#53]
Hello, I get this error when I try to run file test_net.py. Can you show me how to fix it? Thank you.
Traceback (most recent call last):
  File "test_net.py", line 95, in <module>
    main()
  File "test_net.py", line 89, in main
    output_folder=output_folder,
  File "/HIT/hit/engine/inference.py", line 182, in inference
    predictions = compute_on_dataset(model, data_loader, device, logger, mem_active)
  File "/HIT/hit/engine/inference.py", line 139, in compute_on_dataset
    results_dict = compute_on_dataset_2stage(model, data_loader, device, logger)
  File "/HIT/hit/engine/inference.py", line 116, in compute_on_dataset_2stage
    output = model(None, None, None, None, extras=extras, part_forward=1)
  File /miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/HIT/hit/modeling/detector/action_detector.py", line 20, in forward
    result, detector_losses, loss_weight, detector_metrics = self.roi_heads(slow_features, fast_features, boxes, objects, keypoints, extras, part_forward)
  File "/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/HIT/hit/modeling/roi_heads/roi_heads_3d.py", line 13, in forward
    result, loss_action, loss_weight, accuracy_action = self.action(slow_features, fast_features, boxes, objects, keypoints, extras, part_forward)
  File "/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/HIT/hit/modeling/roi_heads/action_head/action_head.py", line 44, in forward
    x, x_pooled, x_objects, x_keypoints, x_pose = self.feature_extractor(slow_features, fast_features, proposals, objects, keypoints, extras, part_forward)
  File "/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/HIT/hit/modeling/roi_heads/action_head/roi_action_feature_extractor.py", line 145, in forward
    ia_feature, res_person, res_object, res_keypoint = self.hit_structure(person_pooled, proposals, object_pooled, objects, hands_pooled, keypoints, memory_person, None, None, phase="rgb")
  File "/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/HIT/hit/modeling/roi_heads/action_head/hit_structure.py", line 213, in forward
    mem_feature, phase)
  File "/HIT/hit/modeling/roi_heads/action_head/hit_structure.py", line 230, in _reduce_dim
    query = self.person_dim_reduce(person)
  File "/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 590, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 586, in _conv_forward
    input, weight, bias, self.stride, self.padding, self.dilation, self.groups
TypeError: conv3d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)                                                       k_2.key.weight            loaded from roi_heads.action.featu

**Comment by joslefaure** [comment]
Fixed in last commit
