### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by hhh804** [joslefaure/HIT#54]
I tried to run 'test_net.py' file, and I got the error:
return self._aggregate(person_boxes, query, person_key, object_key, hand_key, mem_key)
  File "/media/data4/home/HIT/hit/modeling/roi_heads/action_head/hit_structure.py", line 385, in _aggregate
    query = I_block(query, person_key)
  File "/media/data4/home/miniconda3/envs/hit/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/data4/home/HIT/hit/modeling/roi_heads/action_head/hit_structure.py", line 131, in forward
    qk = torch.bmm(query_batch, key_batch)  # n, thw, max_other * thw
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

How can I fix it? Thank you.

**Comment by joslefaure** [comment]
Seems like your cuda version doesn't match your torch version. I recommend using torch=1.7.1 and cuda 10.2

**Comment by hhh804** [comment]
My environment is cuda11.3,torch 1.10.0+cu11.3, python 3.7. When I installed pytorch 1.7.1 with cuda 10.2 I got this error. Help me fix the error, please.

Traceback (most recent call last):
      File "<string>", line 36, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/media/data4/home/HIT/setup.py", line 121, in <module>
        cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
        return distutils.core.setup(**attrs)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
        return run_commands(dist)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
        dist.run_commands()
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
        self.distribution.run_command(command)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/dist.py", line 1208, in run_command
        super().run_command(command)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
        self.build_extensions()
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 670, in build_extensions
        build_ext.build_extensions(self)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
        _build_ext.build_ext.build_extensions(self)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 468, in build_extensions
        self._build_extensions_serial()
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 494, in _build_extensions_serial
        self.build_extension(ext)
      File "/media/data4/homeminiconda3/envs/HIT/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
        _build_ext.build_extension(self, ext)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 556, in build_extension
        depends=ext.depends,
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 500, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1255, in _write_ninja_file_and_compile_objects
        error_prefix='Error compiling objects for extension')
      File "/media/data4/home/miniconda3/envs/HIT/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1555, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    [end of output]

**Comment by MatteoEleouet** [comment]
try cuda 1.7.1
